name: Run Pytest Suite
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-html
    - name: Install ChromeDriver
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install package
      run: pip install -e .
    - name: Run tests
      run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          pytest
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
